import "./globals.css";
import Navbar from "@/components/Navbar/Navbar";
import Footer from "@/components/Footer/Footer";
import { AuthProvider } from "@/context/AuthProvider";

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en" className="">

      <body className={`antialiased bg-white flex flex-col min-h-screen w-full`}>

        <AuthProvider>

          <Navbar />

          <div className="flex-1">
            {children}
          </div>

          <Footer />

        </AuthProvider>

      </body>

    </html >
  );
}